; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ms4000]
platform = espressif8266
framework = arduino
board = esp12e
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld
upload_resetmethod = ck
build_flags = -lstdc++ -lsupc++ -I../tools/nanopb/ -DPB_FIELD_16BIT
upload_speed = 921600
lib_deps = 
	256dpi/MQTT
;	https://github.com/magicshifter/aJson.git
	fortyseveneffects/MIDI Library@^5.0.2
	lathoub/AppleMIDI@^3.3.0
	bblanchon/ArduinoJson@^7.4.3
;	cnmat/OSC@^1.0.0
;   interactive-matter/aJson@0.0.0-alpha+sha.ec56354313
	zserge/jsmn@0.0.0-alpha+sha.053d3cd292
;   thijse/EEPROMEx@0.0.0-alpha+sha.09d7586108
	tzapu/WiFiManager@^2.0.17
	mbed-intrinseca/Nanopb@0.0.0+sha.e08406101222

[env:ms4000-debug]
platform = espressif8266
framework = arduino
board = esp12e
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld
build_type = debug
upload_resetmethod = ck
build_flags = -lstdc++ -lsupc++ -I../tools/nanopb/ -DPB_FIELD_16BIT -DUSE_GDBSTUB_DEBUGGING
upload_speed = 921600
lib_deps = 
	256dpi/MQTT
;	https://github.com/magicshifter/aJson.git
	fortyseveneffects/MIDI Library@^5.0.2
	lathoub/AppleMIDI@^3.3.0
	bblanchon/ArduinoJson@^7.4.3
;	cnmat/OSC@^1.0.0
;   interactive-matter/aJson@0.0.0-alpha+sha.ec56354313
	zserge/jsmn@0.0.0-alpha+sha.053d3cd292
;   thijse/EEPROMEx@0.0.0-alpha+sha.09d7586108
	tzapu/WiFiManager@^2.0.17
	mbed-intrinseca/Nanopb@0.0.0+sha.e08406101222
; monitor_speed = 115200
; upload_speed = 921600

